Ext.ns("App");
App.importJs = {
	AppRoleView : [ __ctxPath + "/js/system/AppRoleView.js",
			__ctxPath + "/ext3/ux/CheckTreePanel.js",
			__ctxPath + "/js/system/RoleGrantRightView.js",
			__ctxPath + "/js/system/AppRoleForm.js" ],
	UserSubView : [ __ctxPath + "/js/system/UserSubView.js",
			__ctxPath + "/js/system/UserSubForm.js" ],
	PersonalDocumentView : [
			__ctxPath + "/js/document/PersonalDocumentView.js",
			__ctxPath + "/js/document/DocumentView.js",
			__ctxPath + "/js/document/DocumentForm.js",
			__ctxPath + "/js/document/DocumentSharedForm.js",
			__ctxPath + "/js/document/DocFolderForm.js" ],
	DocumentSharedView : [ __ctxPath + "/js/document/DocumentSharedView.js",
			__ctxPath + "/js/document/DocumentSharedDetail.js" ],
	DocFolderSharedView : [
			__ctxPath + "/js/document/FindPublicDocumentView.js",
			__ctxPath + "/js/document/DocFolderView.js",
			__ctxPath + "/js/document/DocFolderForm.js",
			__ctxPath + "/js/document/DocFolderSharedView.js",
			__ctxPath + "/js/document/DocFolderSharedForm.js",
			__ctxPath + "/js/document/DocPrivilegeForm.js",
			__ctxPath + "/js/document/DocPrivilegeView.js" ],
	FindPublicDocumentView : [
			__ctxPath + "/js/document/FindPublicDocumentView.js",
			__ctxPath + "/js/document/PublicDocumentView.js",
			__ctxPath + "/js/document/PublicDocumentDetail.js",
			__ctxPath + "/js/document/NewPublicDocumentForm.js",
			__ctxPath + "/js/document/DocFolderSelector.js" ],
	NewPublicDocumentForm : [
			__ctxPath + "/js/document/NewPublicDocumentForm.js",
			__ctxPath + "/js/document/DocFolderSelector.js" ],
	DocFolderMoveForm : [ __ctxPath + "/js/document/DocFolderMoveForm.js",
			__ctxPath + "/js/document/PersonalDocFolderSelector.js" ],
	NoticeView : [ __ctxPath + "/js/info/NoticeView.js",
			__ctxPath + "/js/info/NoticeForm.js" ],
	ReportTemplateView : [ __ctxPath + "/js/system/ReportTemplateView.js",
			__ctxPath + "/js/system/ReportTemplateForm.js",
			__ctxPath + "/js/system/ReportParamForm.js",
			__ctxPath + "/js/system/ReportParamView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	MessageManageView : [ __ctxPath + "/js/info/MessageManageView.js",
			__ctxPath + "/js/info/MessageForm.js" ],
	PhoneBookView : [ __ctxPath + "/js/communicate/PhoneBookView.js",
			__ctxPath + "/js/communicate/PhoneGroupForm.js",
			__ctxPath + "/js/communicate/PhoneBookForm.js" ],
	DepartmentView : [ __ctxPath + "/js/system/DepartmentView.js",
			__ctxPath + "/js/system/DepartmentForm.js",
			__ctxPath + "/js/system/AppUserView.js",
			__ctxPath + "/ext3/ux/ItemSelector.js",
			__ctxPath + "/ext3/ux/MultiSelect.js",
			__ctxPath + "/js/system/JobPositionForm.js",
			__ctxPath + "/js/system/AppUserForm.js" ],
	AppUserView : [ __ctxPath + "/js/system/AppUserView.js",
			__ctxPath + "/js/system/AppUserForm.js",
			__ctxPath + "/ext3/ux/ItemSelector.js",
			__ctxPath + "/ext3/ux/MultiSelect.js",
			__ctxPath + "/js/system/ResetPasswordForm.js" ],
	ProfileForm : [ __ctxPath + "/js/system/ProfileForm.js",
			__ctxPath + "/js/system/ResetPasswordForm.js" ],
	NewsView : [ __ctxPath + "/js/info/NewsView.js",
			__ctxPath + "/js/info/NewsForm.js",
			__ctxPath + "/js/info/NewsTypeTree.js",
			__ctxPath + "/js/info/NewsTypeForm.js" ],
	NewsTypeView : [ __ctxPath + "/js/info/NewsTypeView.js",
			__ctxPath + "/js/info/NewsTypeForm.js" ],
	CompanyView : [ __ctxPath + "/js/system/CompanyView.js" ],
	FileAttachView : [ __ctxPath + "/js/system/FileAttachView.js",
			__ctxPath + "/js/system/FileAttachDetail.js" ],
	DiaryView : [ __ctxPath + "/js/system/DiaryView.js",
			__ctxPath + "/js/system/DiaryForm.js" ],
	MySubUserDiaryView : [ __ctxPath + "/js/system/MySubUserDiaryView.js",
			__ctxPath + "/js/system/DiaryDetail.js" ],
	PersonalMailBoxView : [
			__ctxPath + "/js/communicate/PersonalMailBoxView.js",
			__ctxPath + "/js/communicate/MailView.js",
			__ctxPath + "/js/communicate/MailForm.js",
			__ctxPath + "/js/communicate/MailFolderForm.js",
			__ctxPath + "/ext3/ux/RowExpander.js" ],
	MailForm : [ __ctxPath + "/js/communicate/MailForm.js" ],
	PersonalPhoneBookView : [
			__ctxPath + "/js/communicate/PersonalPhoneBookView.js",
			__ctxPath + "/js/communicate/PhoneBookView.js",
			__ctxPath + "/js/communicate/PhoneGroupForm.js",
			__ctxPath + "/js/communicate/PhoneBookForm.js" ],
	SharedPhoneBookView : [
			__ctxPath + "/js/communicate/SharedPhoneBookView.js",
			__ctxPath + "/js/communicate/SharedPhoneBookWin.js" ],
	FlowManagerView : [ __ctxPath + "/js/flow/ProTypeForm.js",
			__ctxPath + "/js/flow/ProDefinitionForm.js",
			__ctxPath + "/js/flow/ProDefinitionView.js",
			__ctxPath + "/js/flow/FlowManagerView.js",
			__ctxPath + "/js/flow/ProDefinitionDetail.js",
			__ctxPath + "/js/flow/ProcessRunStart.js",
			__ctxPath + "/js/flow/ProDefinitionSetting.js",
			__ctxPath + "/js/flow/MyTaskView.js",
			__ctxPath + "/js/flow/ProcessNextForm.js",
			__ctxPath + "/js/flow/FormDesignWindow.js",
			__ctxPath + "/js/flow/FormEditorWindow.js",
			__ctxPath + "/js/flowDesign/FlowDesignerWindow.js" ],
	NewProcess : [ __ctxPath + "/js/flow/NewProcess.js",
			__ctxPath + "/js/flow/ProDefinitionDetail.js",
			__ctxPath + "/js/flow/ProDefinitionView.js",
			__ctxPath + "/js/flow/ProcessRunStart.js" ],
	ProcessRunView : [ __ctxPath + "/js/flow/ProcessRunView.js",
			__ctxPath + "/js/flow/ProcessRunDetail.js",
			__ctxPath + "/js/flow/ProcessRunStart.js" ],
	MyTaskView : [ __ctxPath + "/js/flow/MyTaskView.js",
			__ctxPath + "/js/flow/ChangeTaskView.js",
			__ctxPath + "/js/flow/ProcessNextForm.js" ],
	ProcessRunFinishView : [ __ctxPath + "/js/flow/ProcessRunFinishView.js",
			__ctxPath + "/js/flow/ProcessRunDetail.js" ],
	BookManageView : [ __ctxPath + "/js/admin/BookManageView.js",
			__ctxPath + "/js/admin/BookView.js",
			__ctxPath + "/js/admin/BookForm.js",
			__ctxPath + "/js/admin/BookTypeForm.js",
			__ctxPath + "/js/admin/BookBorrowForm.js",
			__ctxPath + "/js/admin/BookAmountForm.js" ],
	BookTypeView : [ __ctxPath + "/js/admin/BookTypeView.js",
			__ctxPath + "/js/admin/BookTypeForm.js" ],
	BookBorrowView : [ __ctxPath + "/js/admin/BookBorrowView.js",
			__ctxPath + "/js/admin/BookBorrowForm.js",
			__ctxPath + "/js/admin/BookReturnForm.js" ],
	BookReturnView : [ __ctxPath + "/js/admin/BookReturnView.js",
			__ctxPath + "/js/admin/BookReturnForm.js" ],
	OfficeGoodsManageView : [ __ctxPath + "/js/admin/OfficeGoodsManageView.js",
			__ctxPath + "/js/admin/OfficeGoodsTypeForm.js",
			__ctxPath + "/js/admin/OfficeGoodsView.js",
			__ctxPath + "/js/admin/OfficeGoodsForm.js" ],
	InStockView : [ __ctxPath + "/js/admin/InStockView.js",
			__ctxPath + "/js/admin/InStockForm.js" ],
	GoodsApplyView : [ __ctxPath + "/js/admin/GoodsApplyView.js",
			__ctxPath + "/js/admin/GoodsApplyForm.js" ],
	CarView : [ __ctxPath + "/js/admin/CarView.js",
			__ctxPath + "/js/admin/CarForm.js" ],
	CartRepairView : [ __ctxPath + "/js/admin/CartRepairView.js",
			__ctxPath + "/js/admin/CartRepairForm.js" ],
	CarApplyView : [ __ctxPath + "/js/admin/CarApplyView.js",
			__ctxPath + "/js/admin/CarApplyForm.js" ],
	AppointmentView : [ __ctxPath + "/js/task/AppointmentView.js",
			__ctxPath + "/js/task/AppointmentForm.js" ],
	CalendarPlanView : [ __ctxPath + "/js/task/CalendarPlanView.js",
			__ctxPath + "/js/task/CalendarPlanForm.js",
			__ctxPath + "/js/task/CalendarPlanFinishForm.js" ],
	MyPlanTaskView : [ __ctxPath + "/js/task/CalendarPlanView.js",
			__ctxPath + "/js/task/CalendarPlanForm.js",
			__ctxPath + "/js/task/CalendarPlanFinishForm.js",
			__ctxPath + "/ext3/ux/caltask/e2cs_zh_CN.js",
			__ctxPath + "/ext3/ux/caltask/calendar.gzjs",
			__ctxPath + "/ext3/ux/caltask/scheduler.gzjs",
			__ctxPath + "/ext3/ux/caltask/monthview.gzjs",
			__ctxPath + "/ext3/ux/caltask/weekview.gzjs",
			__ctxPath + "/ext3/ux/caltask/dayview.gzjs",
			__ctxPath + "/ext3/ux/caltask/task.gzjs",
			__ctxPath + "/js/task/MyPlanTaskView.gzjs",
			__ctxPath + "/js/task/CalendarPlanDetailView.js" ],
	PlanTypeView : [ __ctxPath + "/js/task/PlanTypeView.js",
			__ctxPath + "/js/task/PlanTypeForm.js" ],
	WorkPlanView : [ __ctxPath + "/js/task/WorkPlanView.js",
			__ctxPath + "/js/task/NewWorkPlanForm.js" ],
	PersonalWorkPlanView : [ __ctxPath + "/js/task/PersonalWorkPlanView.js",
			__ctxPath + "/js/task/WorkPlanDetail.js" ],
	NewWorkPlanForm : [ __ctxPath + "/js/task/NewWorkPlanForm.js" ],
	DepWorkPlanView : [ __ctxPath + "/js/task/DepWorkPlanView.js",
			__ctxPath + "/js/task/WorkPlanDetail.js" ],
	CustomerView : [ __ctxPath + "/js/customer/CustomerView.js",
			__ctxPath + "/js/customer/CustomerForm.js",
			__ctxPath + "/js/customer/CusLinkmanForm.js",
			__ctxPath + "/js/customer/SendMailForm.js" ],
	CusLinkmanView : [ __ctxPath + "/js/customer/CusLinkmanView.js",
			__ctxPath + "/js/customer/CusLinkmanForm.js" ],
	FixedAssetsManageView : [ __ctxPath + "/js/admin/FixedAssetsManageView.js",
			__ctxPath + "/js/admin/FixedAssetsView.js",
			__ctxPath + "/js/admin/FixedAssetsForm.js",
			__ctxPath + "/js/admin/AssetsTypeForm.js",
			__ctxPath + "/js/admin/DepreWin.js",
			__ctxPath + "/js/admin/WorkGrossWin.js" ],
	DepreTypeView : [ __ctxPath + "/js/admin/DepreTypeForm.js",
			__ctxPath + "/js/admin/DepreTypeView.js" ],
	DepreRecordView : [ __ctxPath + "/js/admin/DepreRecordForm.js",
			__ctxPath + "/js/admin/DepreRecordView.js" ],
	CusConnectionView : [ __ctxPath + "/js/customer/CusConnectionView.js",
			__ctxPath + "/js/customer/CusConnectionForm.js" ],
	ProjectView : [ __ctxPath + "/js/customer/ProjectView.js",
			__ctxPath + "/js/customer/ProjectForm.js",
			__ctxPath + "/js/customer/ContractForm.js",
			__ctxPath + "/js/customer/ContractConfigView.js" ],
	ContractView : [ __ctxPath + "/js/customer/ContractView.js",
			__ctxPath + "/js/customer/ContractForm.js",
			__ctxPath + "/js/customer/ContractConfigView.js" ],
	ProductView : [ __ctxPath + "/js/customer/ProductView.js",
			__ctxPath + "/js/customer/ProductForm.js" ],
	ProviderView : [ __ctxPath + "/js/customer/ProviderView.js",
			__ctxPath + "/js/customer/ProviderForm.js",
			__ctxPath + "/js/customer/SendMailForm.js" ],
	HolidayRecordView : [ __ctxPath + "/js/personal/HolidayRecordView.js",
			__ctxPath + "/js/personal/HolidayRecordForm.js" ],
	DutySectionView : [ __ctxPath + "/js/personal/DutySectionView.js",
			__ctxPath + "/js/personal/DutySectionForm.js" ],
	DutySystemView : [ __ctxPath + "/js/personal/DutySystemView.js",
			__ctxPath + "/js/personal/DutySystemForm.js",
			__ctxPath + "/js/selector/DutySectionSelector.js" ],
	SignInOffView : [ __ctxPath + "/js/personal/SignInOffView.js" ],
	DutyRegisterPersonView : [ __ctxPath
			+ "/js/personal/DutyRegisterPersonView.js" ],
	DutyRegisterView : [ __ctxPath + "/js/personal/DutyRegisterView.js",
			__ctxPath + "/js/personal/DutyRegisterForm.js" ],
	ErrandsRegisterView : [ __ctxPath + "/js/personal/ErrandsRegisterView.js",
			__ctxPath + "/js/personal/ErrandsRegisterDetail.js",
			__ctxPath + "/js/personal/ErrandsRegisterForm.js" ],
	ErrandsRegisterOutView : [
			__ctxPath + "/js/personal/ErrandsRegisterOutView.js",
			__ctxPath + "/js/personal/ErrandsRegisterOutForm.js" ],
	SysConfigView : [ __ctxPath + "/js/system/SysConfigView.js" ],
	NoticeDetail : [ __ctxPath + "/js/info/NoticeDetail.js" ],
	NewsDetail : [ __ctxPath + "/js/info/NewsDetail.js" ],
	PublicDocumentDetail : [ __ctxPath + "/js/document/PublicDocumentDetail.js" ],
	MailDetail : [ __ctxPath + "/js/communicate/MailDetail.js",
			__ctxPath + "/js/communicate/MailForm.js" ],
	CalendarPlanDetail : [ __ctxPath + "/js/task/CalendarPlanDetail.js" ],
	AppointmentDetail : [ __ctxPath + "/js/task/AppointmentDetail.js" ],
	SearchNews : [ __ctxPath + "/js/search/SearchNews.js",
			__ctxPath + "/js/info/NewsDetail.js" ],
	SearchMail : [ __ctxPath + "/js/search/SearchMail.js",
			__ctxPath + "/ext3/ux/RowExpander.js",
			__ctxPath + "/js/communicate/MailView.js",
			__ctxPath + "/js/communicate/MailForm.js" ],
	SearchNotice : [ __ctxPath + "/js/search/SearchNotice.js" ],
	SearchDocument : [ __ctxPath + "/js/search/SearchDocument.js",
			__ctxPath + "/js/document/PublicDocumentDetail.js" ],
	HireIssueView : [ __ctxPath + "/js/hrm/HireIssueView.js",
			__ctxPath + "/js/hrm/HireIssueForm.js",
			__ctxPath + "/js/hrm/HireIssueCheckWin.js" ],
	ResumeView : [ __ctxPath + "/js/hrm/ResumeView.js",
			__ctxPath + "/js/hrm/ResumeForm.js" ],
	NewsCommentView : [ __ctxPath + "/js/info/NewsCommentView.js",
			__ctxPath + "/ext3/ux/RowExpander.js" ],
	DicManager : [ __ctxPath + "/js/ent/system/GlobalTypeForm.js",
			__ctxPath + "/js/ent/system/DicManager.js",
			__ctxPath + "/js/ent/system/DicTypeChangeWin.js",
			__ctxPath + "/js/system/DictionaryForm.js" ],
	SalaryItemView : [ __ctxPath + "/js/hrm/SalaryItemForm.js",
			__ctxPath + "/js/hrm/SalaryItemView.js" ],
	StandSalaryForm : [ __ctxPath + "/js/hrm/StandSalaryForm.js",
			__ctxPath + "/js/hrm/StandSalaryItemView.js",
			__ctxPath + "/js/selector/SalaryItemSelector.js" ],
	StandSalaryView : [ __ctxPath + "/js/hrm/StandSalaryView.js",
			__ctxPath + "/js/hrm/StandSalaryForm.js",
			__ctxPath + "/js/hrm/StandSalaryItemView.js",
			__ctxPath + "/js/hrm/CheckStandSalaryForm.js",
			__ctxPath + "/js/hrm/CheckStandSalaryItemView.js",
			__ctxPath + "/js/selector/SalaryItemSelector.js" ],
	JobChangeForm : [ __ctxPath + "/js/hrm/JobChangeForm.js",
			__ctxPath + "/js/selector/EmpProfileSelector.js" ],
	JobChangeView : [ __ctxPath + "/js/hrm/JobChangeView.js",
			__ctxPath + "/js/hrm/JobChangeForm.js",
			__ctxPath + "/js/selector/EmpProfileSelector.js",
			__ctxPath + "/js/hrm/CheckJobChangeWin.js" ],
	JobView : [ __ctxPath + "/js/hrm/JobView.js",
			__ctxPath + "/js/hrm/JobForm.js",
			__ctxPath + "/js/hrm/RecoveryJobWin.js" ],
	EmpProfileForm : [ __ctxPath + "/js/hrm/EmpProfileForm.js" ],
	EmpProfileView : [ __ctxPath + "/js/hrm/EmpProfileView.js",
			__ctxPath + "/js/hrm/EmpProfileForm.js",
			__ctxPath + "/js/hrm/CheckEmpProfileForm.js",
			__ctxPath + "/js/hrm/RecoveryProfileWin.js" ],
	SalaryPayoffForm : [ __ctxPath + "/js/hrm/SalaryPayoffForm.js",
			__ctxPath + "/js/selector/EmpProfileSelector.js" ],
	SalaryPayoffView : [ __ctxPath + "/js/hrm/SalaryPayoffForm.js",
			__ctxPath + "/js/selector/EmpProfileSelector.js",
			__ctxPath + "/js/hrm/CheckSalaryPayoffForm.js",
			__ctxPath + "/js/hrm/SalaryPayoffView.js" ],
	PersonalSalaryView : [ __ctxPath + "/js/personal/PersonalSalaryView.js",
			__ctxPath + "/ext3/ux/RowExpander.js" ],
	SystemLogView : [ __ctxPath + "/js/system/SystemLogView.js" ],
	MyProcessRunView : [ __ctxPath + "/js/flow/MyProcessRunView.js",
			__ctxPath + "/js/flow/ProcessRunDetail.js" ],
	StockPlanSummaryView : [
			__ctxPath + "/js/ent/purchase/StockPlanSummaryView.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	OpponentView : [ __ctxPath + "/js/ent/crm/OpponentView.js",
			__ctxPath + "/js/ent/crm/OpponentForm.js" ],
	ClientForm : [ __ctxPath + "/js/ent/core/CusProTypeSelector.js",
			__ctxPath + "/js/ent/crm/ClientForm.js" ],
	ClientThreadView : [ __ctxPath + "/js/ent/crm/ClientThreadView.js",
			__ctxPath + "/js/ent/crm/ClientThreadForm.js",
			__ctxPath + "/js/ent/crm/SubmitReportForm.js",
			__ctxPath + "/js/ent/core/ClientSelector.js",
			__ctxPath + "/js/ent/crm/ClientAssign.js",
			__ctxPath + "/js/ent/crm/ClientTurnToForm.js",
			__ctxPath + "/js/ent/crm/ClientDetect.js",
			__ctxPath + "/js/ent/crm/ClientThreadWin.js",
			__ctxPath + "/js/ent/core/CusProTypeSelector.js",
			__ctxPath + "/js/ent/crm/ClientContractWin.js",
			__ctxPath + "/js/ent/crm/ClientContractForm.js",
			__ctxPath + "/js/ent/crm/ClientFollowWin.js",
			__ctxPath + "/js/ent/crm/ClientFollowForm.js" ],
	SupplierView : [ __ctxPath + "/js/ent/crm/SupplierView.js",
			__ctxPath + "/js/ent/crm/SupplierForm.js" ],
	ClientReportView : [ __ctxPath + "/js/ent/crm/ClientReportView.js",
			__ctxPath + "/js/ent/crm/ClientReportForm.js",
			__ctxPath + "/js/ent/crm/ClientReportDeal.js" ],
	ClientPoolView : [ __ctxPath + "/js/ent/crm/ClientPoolView.js",
			__ctxPath + "/js/ent/crm/ClientManageWin.js",
			__ctxPath + "/js/ent/crm/ClientReAssign.js" ],
	ClientManageView : [ __ctxPath + "/js/ent/crm/ClientManageView.js",
			__ctxPath + "/js/ent/crm/ClientThreadForm.js",
			__ctxPath + "/js/ent/crm/ClientAssign.js",
			__ctxPath + "/js/ent/crm/ClientForm.js",
			__ctxPath + "/js/ent/crm/SubmitReportForm.js",
			__ctxPath + "/js/ent/crm/ClientOpLogWin.js",
			__ctxPath + "/js/ent/crm/ClientManageWin.js",
			__ctxPath + "/js/ent/crm/ClientSharedForm.js",
			__ctxPath + "/js/ent/core/CusProTypeSelector.js",
			__ctxPath + "/js/ent/crm/ClientTurnToForm.js",
			__ctxPath + "/js/ent/crm/ClientContractWin.js",
			__ctxPath + "/js/ent/crm/ClientContractForm.js",
			__ctxPath + "/js/ent/crm/ClientFollowWin.js",
			__ctxPath + "/js/ent/crm/ClientFollowForm.js" ],
	SalesChanceView : [ __ctxPath + "/js/ent/crm/SalesChanceView.js",
			__ctxPath + "/js/ent/crm/SalesChanceForm.js",
			__ctxPath + "/js/ent/core/ClientSelector.js",
			__ctxPath + "/js/selector/UserSelector.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	StockPlanView : [ __ctxPath + "/js/ent/marketing/StockPlanView.js",
			__ctxPath + "/js/ent/marketing/StockPlanForm.js",
			__ctxPath + "/js/ent/core/ClientSelector.js",
			__ctxPath + "/js/ent/core/ReportPriceDetailProModalSelector.js" ],
	SampleApplyView : [ __ctxPath + "/js/ent/marketing/SampleApplyView.js",
			__ctxPath + "/js/ent/marketing/SampleApplyForm.js",
			__ctxPath + "/js/ent/marketing/SampleApplySubmitForm.js",
			__ctxPath + "/js/ent/marketing/SampleApplyDetail.js" ],
	SampleTempView : [ __ctxPath + "/js/ent/marketing/SampleTempView.js",
			__ctxPath + "/js/ent/marketing/SampleTempForm.js" ],
	SampleStockView : [ __ctxPath + "/js/ent/core/AllClientSelector.js",
			__ctxPath + "/js/ent/marketing/SampleStockView.js",
			__ctxPath + "/js/ent/marketing/SampleStockForm.js",
			__ctxPath + "/js/ent/marketing/SampleGiveForm.js",
			__ctxPath + "/js/ent/marketing/SampleGetForm.js",
			__ctxPath + "/js/ent/core/CusProTypeSelector.js",
			__ctxPath + "/js/ent/marketing/SampleApplyBackForm.js" ],
	SampleReceiveView : [ __ctxPath + "/js/ent/marketing/SampleReceiveView.js",
			__ctxPath + "/js/ent/marketing/SampleReceiveForm.js",
			__ctxPath + "/js/ent/marketing/SampleReceiveDetail.js",
			__ctxPath + "/js/ent/marketing/SampleFollowDetailWin.js" ],
	SampleFollowView : [ __ctxPath + "/js/ent/marketing/SampleFollowView.js",
			__ctxPath + "/js/ent/marketing/SampleFollowForm.js",
			__ctxPath + "/js/ent/marketing/SampleFollowDetail.js" ],
	ReportPriceView : [ __ctxPath + "/js/ent/marketing/ReportPriceView.js",
			__ctxPath + "/js/ent/marketing/ReportPriceForm.js",
			__ctxPath + "/js/ent/marketing/ReportPriceCheckForm.js",
			__ctxPath + "/js/ent/marketing/ReportPriceDetail.js",
			__ctxPath + "/js/ent/marketing/SimpleTempCheckWin.js",
			__ctxPath + "/js/ent/core/ClientContractSelector.js",
			__ctxPath + "/js/ent/core/ReportDetailSelector.js" ],
	CurrencyView : [ __ctxPath + "/js/ent/system/CurrencyView.js",
			__ctxPath + "/js/ent/system/CurrencyForm.js" ],
	TravelApplyView : [ __ctxPath + "/js/ent/core/ClientContractSelector.js",
			__ctxPath + "/js/ent/marketing/TravelApplyView.js",
			__ctxPath + "/js/ent/marketing/TravelApplyForm.js",
			__ctxPath + "/js/ent/marketing/TravalDetailGrid.js",
			__ctxPath + "/js/ent/marketing/TravalDetailForm.js",
			__ctxPath + "/js/ent/marketing/TravelApplyCheckForm.js",
			__ctxPath + "/js/ent/marketing/TravelSummary.js",
			__ctxPath + "/js/ent/marketing/TravelApplyDisplay.js",
			__ctxPath + "/js/ent/marketing/TravalDetailGridDisplay.js",
			__ctxPath + "/js/ent/marketing/TravalClientSelector.js" ],
	CusComplaintView : [ __ctxPath + "/js/ent/crm/CusComplaintView.js",
			__ctxPath + "/js/ent/crm/CusComplaintForm.js",
			__ctxPath + "/js/ent/crm/CusComplaintDocForm.js",
			__ctxPath + "/js/ent/crm/CusComplaintDetail.js" ],
	GlobalTypeManager : [ __ctxPath + "/js/ent/system/GlobalTypeManager.js",
			__ctxPath + "/js/ent/system/GlobalTypeForm.js" ],
	ProModalManager : [ __ctxPath + "/js/ent/system/ProModalManager.js",
			__ctxPath + "/js/ent/system/ProductModalForm.js",
			__ctxPath + "/js/ent/system/GlobalTypeForm.js" ],
	ClientFollowView : [ __ctxPath + "/js/ent/crm/ClientFollowView.js",
			__ctxPath + "/js/ent/crm/ClientFollowForm.js" ],
	SalesOrderView : [ __ctxPath + "/js/ent/sales/SalesOrderView.js",
			__ctxPath + "/js/ent/sales/SalesOrderForm.js",
			__ctxPath + "/js/ent/sales/SalesOrderDetail.js",
			__ctxPath + "/js/ent/sales/SalesOrderGrid.js",
			__ctxPath + "/js/ent/sales/SalesDetailForm.js",
			__ctxPath + "/js/ent/sales/OrderAttachsView.js",
			__ctxPath + "/js/ent/sales/OrderAttachsForm.js",
			__ctxPath + "/js/archive/ArchivesDocForm.js",
			__ctxPath + "/js/system/FileAttachDetail.js",
			__ctxPath + "/js/ent/sales/SalesDetailView.js",
			__ctxPath + "/js/ent/core/StockSearchWin.js" ],
	TravelApplyCheckView : [
			__ctxPath + "/js/ent/core/ClientContractSelector.js",
			__ctxPath + "/js/ent/marketing/TravelApplyCheckView.js",
			__ctxPath + "/js/ent/marketing/TravelApplyForm.js",
			__ctxPath + "/js/ent/marketing/TravalDetailGrid.js",
			__ctxPath + "/js/ent/marketing/TravalDetailForm.js",
			__ctxPath + "/js/ent/marketing/TravelApplyCheckForm.js",
			__ctxPath + "/js/ent/marketing/TravelSummary.js",
			__ctxPath + "/js/ent/marketing/TravelApplyDisplay.js",
			__ctxPath + "/js/ent/marketing/TravalDetailGridDisplay.js" ],
	SalesShipOutView : [ __ctxPath + "/js/ent/sales/SalesShipOutView.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckForm.js",
			__ctxPath + "/js/ent/core/SalesOrderSelector.js",
			__ctxPath + "/js/ent/sales/SalesShipForm.js",
			__ctxPath + "/js/ent/core/StockSearchWin.js" ],
	WarehouseView : [ __ctxPath + "/js/ent/stock/WarehouseView.js",
			__ctxPath + "/js/ent/stock/WarehouseForm.js",
			__ctxPath + "/js/ent/stock/StockMatView.js",
			__ctxPath + "/js/ent/stock/StockMatForm.js" ],
	StockCheckView : [ __ctxPath + "/js/ent/stock/StockCheckView.js",
			__ctxPath + "/js/ent/stock/StockCheckDetail.js",
			__ctxPath + "/js/ent/stock/StockCheckForm.js",
			__ctxPath + "/js/ent/stock/CheckToOrderDetail.js" ],
	SkCheckDetailView : [ __ctxPath + "/js/ent/stock/SkCheckDetailView.js",
			__ctxPath + "/js/ent/stock/SkCheckDetailForm.js" ],
	WarehouseManageView : [ __ctxPath + "/js/ent/stock/WarehouseManageView.js",
			__ctxPath + "/js/ent/stock/WarehouseForm.js",
			__ctxPath + "/js/ent/stock/StockOrderForm.js",
			__ctxPath + "/js/ent/stock/SkOrderDetailView.js",
			__ctxPath + "/js/ent/stock/StockCheckForm.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ],
	CalUnitManager : [ __ctxPath + "/js/ent/system/CalUnitManager.js",
			__ctxPath + "/js/ent/system/CalUnitForm.js",
			__ctxPath + "/js/ent/system/GlobalTypeForm.js" ],
	StockPlanCheckView : [
			__ctxPath + "/js/ent/marketing/StockPlanCheckView.js",
			__ctxPath + "/js/ent/marketing/StockCaseForm.js",
			__ctxPath + "/js/ent/marketing/StockConfirmForm.js",
			__ctxPath + "/js/ent/marketing/StockPlanCheckForm.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	ClientContractView : [ __ctxPath + "/js/ent/crm/ClientContractView.js",
			__ctxPath + "/js/ent/crm/ClientContractForm.js" ],
	StockOrderView : [ __ctxPath + "/js/ent/stock/StockOrderView.js",
			__ctxPath + "/js/ent/stock/StockOrderForm.js",
			__ctxPath + "/js/ent/stock/SkOrderDetailView.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js",
			__ctxPath + "/js/ent/stock/StockOrderDetailHistory.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckForm.js" ],
	SkOrderDetailView : [ __ctxPath + "/js/ent/stock/SkOrderDetailView.js",
			__ctxPath + "/js/ent/stock/SkOrderDetailForm.js" ],
	SalesShipBackView : [ __ctxPath + "/js/ent/sales/SalesShipBackView.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckForm.js",
			__ctxPath + "/js/ent/sales/SalesShipBackForm.js",
			__ctxPath + "/js/ent/core/StockSearchWin.js" ],
	FundReturnView : [ __ctxPath + "/js/ent/core/GlobalTypeSelector.js",
			__ctxPath + "/js/ent/finance/FundReturnView.js",
			__ctxPath + "/js/ent/finance/FundOffDetailWin.js",
			__ctxPath + "/js/ent/finance/FundReturnForm.js",
			__ctxPath + "/js/ent/finance/SalesExpenseForm.js",
			__ctxPath + "/js/ent/finance/FundReturnUnExpenseWin.js" ],
	SalesTargetView : [ __ctxPath + "/js/ent/marketing/SalesTargetView.js",
			__ctxPath + "/ext3/ux/ColumnHeaderGroup.js",
			__ctxPath + "/ext3/ux/maximgb/tg/TreeGrid.js" ],
	SalesShipCheckView : [ __ctxPath + "/js/ent/sales/SalesShipCheckForm.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckView.js" ],
	SalesPaidView : [ __ctxPath + "/js/ent/finance/SalesPaidView.js",
			__ctxPath + "/js/ent/finance/SalesPaidForm.js",
			__ctxPath + "/js/ent/finance/SalesPaidCheckForm.js" ],
	SalesExpenseView : [ __ctxPath + "/js/ent/finance/SalesExpenseView.js",
			__ctxPath + "/js/ent/finance/SalesExpenseForm.js" ],
	SalesOutBackView : [ __ctxPath + "/js/ent/sales/SalesOutBackView.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckForm.js" ],
	ClientRecoverView : [ __ctxPath + "/js/ent/crm/ClientRecoverView.js",
			__ctxPath + "/js/ent/crm/ClientManageWin.js" ],
	StockPurchaseView : [ __ctxPath + "/js/ent/stock/StockPurchaseView.js",
			__ctxPath + "/js/ent/stock/StockPurchaseForm.js",
			__ctxPath + "/js/ent/stock/StockPurchaseCheckForm.js",
			__ctxPath + "/js/ent/stock/SkOrderDetailView.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ],
	ClientThreadPublic : [ __ctxPath + "/js/ent/crm/ClientThreadPublic.js",
			__ctxPath + "/js/ent/crm/ClientManageWin.js" ],
	PurchaseOrderView : [ __ctxPath + "/js/ent/purchase/PurchaseOrderView.js",
			__ctxPath + "/js/ent/purchase/PurchaseOrderForm.js",
			__ctxPath + "/js/ent/purchase/PurchaseOrderDetail.js" ],
	SampleApplyCheckView : [
			__ctxPath + "/js/ent/marketing/SampleApplyCheckView.js",
			__ctxPath + "/js/ent/marketing/SampleApplySubmitForm.js" ],
	ReportPriceCheckView : [
			__ctxPath + "/js/ent/marketing/ReportPriceCheckView.js",
			__ctxPath + "/js/ent/marketing/ReportPriceCheckWin.js",
			__ctxPath + "/js/ent/marketing/ReportPriceCheckForm.js",
			__ctxPath + "/js/ent/marketing/ReportPriceDetail.js",
			__ctxPath + "/js/ent/marketing/SimpleTempCheckWin.js",
			__ctxPath + "/js/ent/core/ReportDetailSelector.js" ],
	ReportDetailView : [ __ctxPath + "/js/ent/marketing/ReportDetailView.js" ],
	SampleFollowSearchView : [
			__ctxPath + "/js/ent/marketing/SampleFollowSearchView.js",
			__ctxPath + "/js/ent/marketing/SampleFollowDetail.js" ],
	InputSalesTargetView : [
			__ctxPath + "/js/ent/marketing/InputSalesTargetView.js",
			__ctxPath + "/js/ent/marketing/InputSalesTargetForm.js" ],
	CheckSalesTargetView : [
			__ctxPath + "/js/ent/marketing/CheckSalesTargetView.js",
			__ctxPath + "/js/ent/marketing/CheckSalesTargetForm.js" ],
	ClientOpLogView : [ __ctxPath + "/js/ent/crm/ClientOpLogView.js" ],
	StockAllocateView : [ __ctxPath + "/js/ent/stock/StockAllocateView.js",
			__ctxPath + "/js/ent/stock/StockAllocateForm.js",
			__ctxPath + "/js/ent/stock/SkOrderDetailView.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ],
	DocClerkView : [ __ctxPath + "/js/ent/crm/DocClerkView.js",
			__ctxPath + "/js/ent/crm/DocClerkEditGrid.js" ],
	NewClientView : [ __ctxPath + "/js/ent/crm/NewClientView.js",
			__ctxPath + "/js/ent/crm/ClientManageWin.js" ],
	MyClientView : [ __ctxPath + "/js/ent/sales/MyClientView.js",
			__ctxPath + "/js/ent/sales/MyClientManageWin.js" ],
	StockStartView : [ __ctxPath + "/js/ent/marketing/StockStartView.js",
			__ctxPath + "/js/ent/marketing/StockStartForm.js",
			__ctxPath + "/js/ent/marketing/StockCaseForm.js",
			__ctxPath + "/js/ent/marketing/StockConfirmForm.js",
			__ctxPath + "/js/ent/marketing/StockBackupEdit.js",
			__ctxPath + "/js/ent/core/ProModalSelector.js" ],
	SampleReceiveCheckView : [
			__ctxPath + "/js/ent/marketing/SampleReceiveCheckView.js",
			__ctxPath + "/js/ent/marketing/SampleReceiveForm.js",
			__ctxPath + "/js/ent/marketing/SampleReceiveDetail.js" ],
	SalesFunnelView : [ __ctxPath + "/js/ent/crm/SalesFunnelView.js" ],
	PersonalTipsView : [ __ctxPath + "/js/info/PersonalTipsView.js" ],
	SampleApplyBackView : [
			__ctxPath + "/js/ent/marketing/SampleApplyBackView.js",
			__ctxPath + "/js/ent/marketing/SampleApplyBackForm.js",
			__ctxPath + "/js/ent/marketing/SimpleTempCheckWin.js" ],
	ClientFileView : [ __ctxPath + "/js/ent/crm/ClientFileView.js",
			__ctxPath + "/js/ent/crm/ClientFileForm.js" ],
	WareHouseSampleApplyView : [
			__ctxPath + "/js/ent/sales/WareHouseSampleApplyView.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleApplyForm.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleApplyCheckForm.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleGrid.js" ],
	WareHouseSampleCheckView : [
			__ctxPath + "/js/ent/sales/WareHouseSampleCheckView.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleApplyForm.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleApplyCheckForm.js",
			__ctxPath + "/js/ent/sales/WareHouseSampleGrid.js" ],
	StockCaseView : [ __ctxPath + "/js/ent/marketing/StockCaseView.js",
			__ctxPath + "/js/ent/marketing/StockCaseForm.js",
			__ctxPath + "/js/ent/marketing/StockPlanView.js",
			__ctxPath + "/js/ent/marketing/StockPlanForm.js",
			__ctxPath + "/js/ent/core/ClientSelector.js" ],
	MeetingSumView : [ __ctxPath + "/js/ent/document/MeetingSumView.js",
			__ctxPath + "/js/ent/document/MeetingSumForm.js" ],
	ClientModifyForm : [ __ctxPath + "/js/ent/crm/ClientModifyForm.js" ],
	SalesShDetailView : [ __ctxPath + "/js/ent/sales/SalesShDetailView.js",
			__ctxPath + "/js/ent/finance/InvoiceForm.js" ],
	NewChanceView : [ __ctxPath + "/js/ent/crm/NewChanceView.js",
			__ctxPath + "/js/ent/crm/NewChanceForm.js" ],
	SalesDetailList : [ __ctxPath + "/js/ent/sales/SalesDetailList.js",
			__ctxPath + "/js/ent/sales/SalesDetailWindow.js" ],
	WorkSumView : [ __ctxPath + "/js/ent/document/WorkSumView.js",
			__ctxPath + "/js/ent/document/WorkSumForm.js",
			__ctxPath + "/js/ent/document/WorkSumFormView.js" ],
	ReplyWorkSumView : [ __ctxPath + "/js/ent/document/ReplyWorkSumView.js",
			__ctxPath + "/js/ent/document/ReplyWorkSumForm.js",
			__ctxPath + "/js/ent/document/WorkSumFormView.js" ],
	StockSearchView : [ __ctxPath + "/js/ent/stock/StockSearchView.js",
			__ctxPath + "/js/ent/stock/StockMatView.js",
			__ctxPath + "/js/ent/stock/StockMatDisplay.js",
			__ctxPath + "/js/ent/stock/StockTransferForm.js" ],
	PurchaseDetailView : [
			__ctxPath + "/js/ent/purchase/PurchaseDetailView.js",
			__ctxPath + "/js/ent/purchase/PurchaseDetailForm.js",
			__ctxPath + "/js/ent/purchase/BackGoodsForm.js" ],
	StockTransferView : [ __ctxPath + "/js/ent/stock/StockTransferView.js",
			__ctxPath + "/js/ent/stock/StockTransferForm.js",
			__ctxPath + "/js/ent/stock/CheckToOrderDetail.js",
			__ctxPath + "/js/ent/stock/StockTransferDetail.js",
			__ctxPath + "/js/ent/core/ProStockSelector.js" ],
	SalesDetailView : [ __ctxPath + "/js/ent/sales/SalesDetailView.js" ],
	OtherOutStockView : [ __ctxPath + "/js/ent/stock/OtherOutStockForm.js",
			__ctxPath + "/js/ent/stock/OtherOutStockView.js",
			__ctxPath + "/js/ent/core/ProStockSelector.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ],
	OtherInStockView : [ __ctxPath + "/js/ent/stock/OtherInStockForm.js",
			__ctxPath + "/js/ent/stock/OtherInStockView.js",
			__ctxPath + "/js/ent/core/ProStockSelector.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ],
	StockStyleView : [ __ctxPath + "/js/ent/marketing/StockStyleView.js",
			__ctxPath + "/js/ent/marketing/StockStyleForm.js" ],
	FinanceReportView : [ __ctxPath + "/js/system/FinanceReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	HummanReportView : [ __ctxPath + "/js/system/HummanReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	SalesReportView : [ __ctxPath + "/js/system/SalesReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	StockMatView : [ __ctxPath + "/js/ent/stock/StockMatView.js",
			__ctxPath + "/js/ent/stock/StockMatDisplay.js",
			__ctxPath + "/js/ent/stock/StockTransferForm.js",
			__ctxPath + "/js/ent/stock/CheckToOrderDetail.js" ],
	ClientReportJasperView : [
			__ctxPath + "/js/system/report/ClientReportJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	SampleReceiveReportJasperView : [
			__ctxPath + "/js/system/report/SampleReceiveReportJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	NewClientSalesShipReportJasperView : [
			__ctxPath
					+ "/js/system/report/NewClientSalesShipReportJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	StockPurchaseCheckView : [
			__ctxPath + "/js/ent/stock/StockPurchaseCheckView.js",
			__ctxPath + "/js/ent/stock/StockPurchaseCheckForm.js" ],
	SalesPaidDetailView : [
			__ctxPath + "/js/ent/finance/SalesPaidDetailView.js",
			__ctxPath + "/js/ent/sales/SalesShipCheckForm.js" ],
	PurchaseApplyView : [ __ctxPath + "/js/ent/purchase/PurchaseApplyView.js",
			__ctxPath + "/js/ent/sales/SalesOrderDetail.js" ],
	SalesRankJasperView : [
			__ctxPath + "/js/system/report/SalesRankJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	SalesDetailJasperView : [
			__ctxPath + "/js/system/report/SalesDetailJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	SalesProcStyleSumJasperView : [
			__ctxPath + "/js/system/report/SalesProcStyleSumJasperView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	purchaseDetailReportView : [
			__ctxPath + "/js/system/report/purchaseDetailReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	StoreHouseReportView : [
			__ctxPath + "/js/system/report/StoreHouseReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	StockReportView : [ __ctxPath + "/js/system/report/StockReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	VerificationDetailReportView : [
			__ctxPath + "/js/system/report/VerificationDetailReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	FundReturnReportView : [
			__ctxPath + "/js/system/report/FundReturnReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	UnFundReturnReportView : [
			__ctxPath + "/js/system/report/UnFundReturnReportView.js",
			__ctxPath + "/js/system/ReportTemplatePreview.js",
			__ctxPath + "/ext3/ux/ext-basex.js" ],
	SampleApplyStockView : [
			__ctxPath + "/js/ent/stock/SampleApplyStockView.js",
			__ctxPath + "/js/ent/stock/OtherOutStockForm.js",
			__ctxPath + "/js/ent/core/ProStockSelector.js",
			__ctxPath + "/js/ent/stock/StockOrderDetail.js" ]
};