Ext.ns("App");
App.importJs = {

	// desktop
	OECP_portal_PortalView : [
		__ctxPath + "/ext-oecp/ui/Button.js",
		__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
		__ctxPath + "/ext-oecp/core/ExtUtil.js",
		__ctxPath + "/js/component/portal/PortletSettingWindow.js",
		__ctxPath + "/js/component/portal/PortletSelectWindow.js",
             __ctxPath + "/js/component/portal/PortalView.js"
             ],
    Ext_ensible_cal_Canlendar : [
		__ctxPath + "/extensible/lib/extensible-all-debug.js?_dc=1.0.2",
		__ctxPath + "/extensible/examples/examples.js?_dc=1.0.2",
		__ctxPath + "/ext-oecp/ui/canlendar/Canlendar.js",
		__ctxPath + "/ext-oecp/ui/canlendar/MemoryEventStore.js"
	            ],
	// permission
	OECP_permission_PermissionManagerView : [
			__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/js/component/permission/PermissionEditWindow.js",
			__ctxPath + "/js/component/permission/RoleSelectWindow.js",
			__ctxPath + "/js/component/permission/PermissionManagerView.js"],
	// user
	OECP_user_UserGridView : [__ctxPath + "/extjs/ux/MultiSelect.js",
			__ctxPath + "/extjs/ux/ItemSelector.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/js/component/core/OrgComboBox.js",
			__ctxPath + "/js/component/user/UserWin.js",
			__ctxPath + "/js/component/user/UserGridView.js"],
	// orgManage
	OECP_org_OrgManagerPanel : [
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath
					+ "/js/component/OrgManage/OECP_CheckboxSelectionModel.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormPanel.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormWindow.js",
			__ctxPath + "/js/component/OrgManage/OECP_TreeFormView.js",
			__ctxPath + "/js/component/OrgManage/OrgManageView.js"],
	// role
	OECP_role_RoleView : [__ctxPath + "/extjs/ux/MultiSelect.js",
			__ctxPath + "/extjs/ux/ItemSelector.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/ext-oecp/ui/TreeGridPanel.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormWindow.js",
			__ctxPath + "/js/component/Role/OECP_CheckboxTreeWindow.js",
			__ctxPath + "/js/component/Role/OECP_RoleAppointWindow.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormPanel.js",
			__ctxPath + "/js/component/Role/RoleView.js"],

	// function
	OECP_bc_func_BCFunctionView : [__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/js/component/function/MDResourceChooseComb.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/js/component/function/FunctionEditForm.js",
			__ctxPath + "/js/component/function/FunctionUIEditForm.js",
			__ctxPath + "/js/component/function/FunctionUIGridPanel.js",
			__ctxPath + "/js/component/function/UIElementGrid.js",
			__ctxPath + "/js/component/function/BCFunctionView.js"],
	//bizComponet 组件注册
	OECP_BizComponent_BizComponentView : [
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/extjs/ux/CheckColumn.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridPanel.js",
			__ctxPath + "/ext-oecp/core/Toast.js",
			__ctxPath + "/js/component/bizComponent/BizComponentView.js"],
	//bizDepend 组件依赖
	OECP_BizDepend_BizDependView : [
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/extjs/ux/CheckColumn.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/ext-oecp/core/Toast.js",
			__ctxPath + "/ext-oecp/ui/GridPanel.js",
			__ctxPath + "/js/component/bizDepend/BizDependView.js"
	
	],		
	// bizservice
	OECP_BizService_BizServiceView : [
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/extjs/ux/CheckColumn.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/RefField.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/QueryColumnModel.js",
			__ctxPath + "/ext-oecp/ui/QueryWindow.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailPanel.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailEditPanel.js",
			__ctxPath + "/js/component/bizService/BizServiceView.js"],

	// department
	OECP_department_DepartmentManageView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/js/component/core/DeptComboBox.js",
			__ctxPath + "/js/component/department/DepartmentManageView.js"],

	// bpm def
	OECP_bpm_ProcessDefView : [
			__ctxPath + "/extjs/ux/fileuploadfield/FileUploadField.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/js/component/bpm/definition/ProcessDefView.js",
			__ctxPath + "/js/component/bpm/actionUtil.js"],
	// bpm instance
	OECP_bpm_ProcessInstanceView : [
			__ctxPath +"/ext-oecp/ui/GridPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceHisView.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceView.js",
			__ctxPath + "/js/component/bpm/actionUtil.js"],
	// bpm undo task
	OECP_bpm_PersonalTaskView : [
			__ctxPath +"/ext-oecp/ui/GridPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath +"/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath + "/js/component/bpmperson/bpmPersonActionUtil.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceHisView.js",
			__ctxPath + "/js/component/bpm/undotask/PersonalTaskView.js",
			__ctxPath + "/js/component/bpm/actionUtil.js"],	
	// bpm done task
	OECP_bpm_PersonalDoneTaskView : [
			__ctxPath +"/ext-oecp/ui/GridPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath +"/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceHisView.js",
			__ctxPath + "/js/component/bpm/donetask/PersonalDoneTaskView.js",
			__ctxPath + "/js/component/bpm/actionUtil.js"],				
	// bpm vir def
	OECP_bpm_VirProcessDefView : [
			__ctxPath + "/extjs/ux/fileuploadfield/FileUploadField.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath +"/extjs/ux/MultiSelect.js",
			__ctxPath +"/extjs/ux/ItemSelector.js",
			__ctxPath +"/ext-oecp/ui/TreeComboBox.js",
			__ctxPath +"/js/component/core/OrgComboBox.js",
			__ctxPath +"/js/component/user/UserWin.js",
			__ctxPath + "/js/component/user/UserGridView.js",
			__ctxPath + "/js/component/bpm/config/VirProcessDefView.js",
			__ctxPath + "/js/component/bpm/actionUtil.js",
			__ctxPath + "/js/component/Role/RoleView.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/js/component/core/FunComboBox.js"],
			
	// bpm person undo task
	OECP_bpmperson_PersonalTaskView : [
			__ctxPath +"/ext-oecp/ui/GridPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath +"/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailPanel.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailEditPanel.js",
			__ctxPath +"/ext-oecp/ui/combo/EnumsCombo.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceHisView.js",
			__ctxPath + "/js/component/bpmperson/undotask/PersonalTaskView.js",
			__ctxPath + "/js/component/bpmperson/bpmPersonActionUtil.js"],	
	// bpm person done task
	OECP_bpmperson_PersonalDoneTaskView : [
			__ctxPath +"/ext-oecp/ui/GridPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath +"/js/component/user/updatePassWord.js",
			__ctxPath +"/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath +"/extjs/ux/GroupSummary.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/extjs/ux/CheckColumn.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailPanel.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailEditPanel.js",
			__ctxPath +"/ext-oecp/ui/combo/EnumsCombo.js",
			__ctxPath + "/js/component/bpm/instance/ProcessInstanceHisView.js",
			__ctxPath + "/js/component/bpmperson/donetask/PersonalDoneTaskView.js",
			__ctxPath + "/js/component/bpmperson/bpmPersonActionUtil.js"],		

			
		// bpm agent user
	OECP_Agent_AgentUserView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/UserCombo.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserConWindow.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserPanel.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserBaseView.js",
			__ctxPath + "/js/component/bpm/agentuser/AgentUserView.js"],
			
	// bpm myagent user
	OECP_MyAgent_MyAgentUserView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath +"/ext-oecp/ui/Button.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserConWindow.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserPanel.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserBaseView.js",
			__ctxPath + "/js/component/bpmperson/myagentuser/MyAgentUserView.js"],
	// post
	OECP_post_PostManageView : [__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/js/component/core/DeptComboBox.js",
			__ctxPath + "/js/component/post/ParentPostSelectComboBox.js",
			__ctxPath + "/js/component/post/PostManageView.js"],

	// dataPermission
	OECP_dataPermission_DataPermissionManageView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/ext-oecp/ui/combo/EnumsCombo.js",
			__ctxPath + "/js/component/core/FunComboBox.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormPanel.js",
			__ctxPath + "/js/component/OrgManage/OECP_FormWindow.js",
			__ctxPath + "/ext-oecp/ui/QueryWindow.js",
			__ctxPath + "/ext-oecp/ui/RefGridEditor.js",
			__ctxPath + "/ext-oecp/ui/QueryColumnModel.js",
			__ctxPath + "/js/component/dataPermission/MDResourceFormWindow.js",
			__ctxPath
					+ "/js/component/dataPermission/DataPermissionManageView.js"],

	// bizTypeConfig 业务类型定义（单据流）
	OECP_BillFlow_BillFlowView : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/ext-oecp/ui/FormWindow.js",
			__ctxPath + "/extjs/ux/CheckColumn.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/js/component/core/FunComboBox.js",
			__ctxPath + "/js/component/billflowMng/BillFlowConfigWindow.js",
			__ctxPath + "/js/component/billflowMng/BizTypePanel.js",
			__ctxPath + "/js/component/billflowMng/BillFlowView.js"],
	// BCEventManager 业务事件管理
	OECP_bcevent_BCEventView : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/ext-oecp/ui/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/combo/BCEventCombo.js",
			__ctxPath + "/js/component/bcevent/EventPanel.js",
			__ctxPath + "/js/component/bcevent/ListenerPanel.js",
			__ctxPath + "/js/component/bcevent/BCEventView.js"],
			
	// 事件监听配置管理		
	OECP_bcevent_BCEventConfig : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
		    __ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/ext-oecp/ui/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/combo/BCEventCombo.js",
			__ctxPath + "/js/component/bcevent/EventPanel.js",
			__ctxPath + "/js/component/bcevent/ListenerPanel.js",
			__ctxPath + "/js/component/bcevent/BCEventConfig.js"],			
			
    // 事件错误日志			
	OECP_bcevent_BCEventErrorLog : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath + "/ext-oecp/ui/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/GridRefField.js",
			__ctxPath + "/ext-oecp/ui/combo/BCCombo.js",
			__ctxPath + "/ext-oecp/ui/combo/BCEventCombo.js",
			__ctxPath + "/js/component/bcevent/EventPanel.js",
			__ctxPath + "/js/component/bcevent/ListenerPanel.js",
			__ctxPath + "/js/component/bcevent/BCEventErrorLog.js"],				
			
	// 主数据资源管理
	OECP_mdresource_MDResourceManageView : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailPanel.js",
			__ctxPath + "/ext-oecp/ui/MasterDetailEditPanel.js",
			__ctxPath + "/extjs/ux/ux-all.js",
			__ctxPath + "/ext-oecp/ui/RefField.js",
			__ctxPath + "/ext-oecp/ui/RefGridEditor.js",
			__ctxPath + "/js/component/mdresource/MDResourceManageView.js",
			__ctxPath + "/js/component/mdresource/MDResourceEditWindow.js"],
	// 界面视图分配
	OECP_uiview_FunViewAssignView : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/extjs/ext-basex.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/AccordionTreePanel.js",
			__ctxPath + "/ext-oecp/ui/combo/OECPComboRef.js",
			__ctxPath + "/js/core/AppUtil.js",
			__ctxPath + "/js/component/uiview/FunViewAssignWindow.js",
			__ctxPath + "/js/component/uiview/FunViewAssignView.js"],
			
	OECP_ui_view_FunViewMngPanel :[
           __ctxPath + "/js/core/AppUtil.js",
			__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/grid/OECPGrid.js",
			__ctxPath + "/ext-oecp/ui/combo/EnumsCombo.js",
			__ctxPath + "/ext-oecp/ui/grid/GridSummary.js",
			__ctxPath + "/ext-oecp/ui/grid/LockingGridView_fixed.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/AccordionTreePanel.js",
			__ctxPath + "/ext-oecp/ui/combo/OECPComboRef.js",
			__ctxPath + "/ext-oecp/core/Toast.js",
			__ctxPath + "/js/component/uiview/FunViewAssignWindow.js",
			__ctxPath + "/js/component/uiview/FunViewAssignView.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngEditPanel.component.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngEditPanel.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngListPanel.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngPanel.js"
	],
	// person
	OECP_Person_PersonView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath+ "/js/component/OrgManage/OECP_CheckboxSelectionModel.js",
			__ctxPath+ "/ext-oecp/ui/CommonWindow.js",
			__ctxPath + "/js/component/person/PostSelectCombo.js",
			__ctxPath + "/js/component/person/OtherPostSelectWindow.js",
			__ctxPath + "/js/component/person/PersonWindow.js",
			__ctxPath + "/js/component/person/PersonPanel.js",
			__ctxPath + "/js/component/person/PersonView.js"],
	// warn
	OECP_Warn_WarnView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath+ "/ext-oecp/ui/CommonWindow.js",
			__ctxPath+ "/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath + "/js/component/task/TimerBasePanel.js",
			__ctxPath + "/js/component/warn/TimerWarnPanel.js",
			__ctxPath + "/js/component/warn/EventWarnPanel.js",
			__ctxPath + "/js/component/warn/WarnPanel.js",
			__ctxPath + "/js/component/warn/WarnNoticeUser.js",
			__ctxPath + "/js/component/warn/WarnConfigWindow.js",
			__ctxPath + "/js/component/warn/WarnView.js"],
	// task
	OECP_Task_TaskView : [
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/js/component/function/FormWindow.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
			__ctxPath+ "/ext-oecp/ui/CommonWindow.js",
			__ctxPath+ "/ext-oecp/ui/datatimefield/DateTimeField.js",
			__ctxPath + "/js/component/task/TimerBasePanel.js",
			__ctxPath + "/js/component/task/TaskConfigWindow.js",
			__ctxPath + "/js/component/task/AddGroupWindow.js",
			__ctxPath + "/js/component/task/TaskPanel.js",
			__ctxPath + "/js/component/task/TimerPanel.js",
			__ctxPath + "/js/component/task/TaskLogWindow.js",
			__ctxPath + "/js/component/task/TaskView.js"],
			
	OECP_bulletin_BulletinView: [
	         			__ctxPath + "/js/component/function/Toast.js",
	        			__ctxPath + "/js/component/function/FormWindow.js",
	        			__ctxPath + "/ext-oecp/ui/Adapter.js",
	        			__ctxPath + "/ext-oecp/ui/TreeComboBox.js",
	        			__ctxPath + "/ext-oecp/ui/Button.js",
	        			__ctxPath + "/ext-oecp/ui/ToftPanel.js",
	        			__ctxPath+ "/ext-oecp/ui/CommonWindow.js",
	        			__ctxPath+ "/ext-oecp/ui/datatimefield/DateTimeField.js",
	        			__ctxPath + "/js/component/task/TimerBasePanel.js",
	        			__ctxPath + "/js/component/task/TaskConfigWindow.js",
	        			__ctxPath + "/js/component/task/TaskLogWindow.js",
	        			__ctxPath + "/js/component/task/TaskPanel.js",
	        			__ctxPath + "/js/component/task/TimerPanel.js",
	        			__ctxPath + "/js/component/task/TaskLogWindow.js",
	        			//__ctxPath + "/js/component/task/TaskView.js",
	        			__ctxPath + "/js/component/bulletin/BulletinView.js"],		
			
	OECP_report_ManagePanel :[
			__ctxPath + "/ext-oecp/core/ExtUtil.js",
			__ctxPath + "/js/component/function/Toast.js",
			__ctxPath + "/ext-oecp/ui/Button.js",
			__ctxPath + "/ext-oecp/ui/Adapter.js",
			__ctxPath + "/ext-oecp/ui/grid/OECPGrid.js",
			__ctxPath + "/ext-oecp/ui/combo/EnumsCombo.js",
			__ctxPath + "/ext-oecp/ui/grid/GridSummary.js",
			__ctxPath + "/ext-oecp/ui/grid/LockingGridView_fixed.js",
			__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
			__ctxPath + "/ext-oecp/ui/AccordionTreePanel.js",
			__ctxPath + "/ext-oecp/ui/combo/OECPComboRef.js",
			__ctxPath + "/ext-oecp/core/Toast.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngEditPanel.component.js",
			__ctxPath + "/js/component/uiview/editor/js/FunViewMngEditPanel.js",
			__ctxPath + "/js/component/rptsetting/ReportViewDesignPanel.js",
			__ctxPath + "/js/component/rptsetting/ReportList.js"
	],
	// 查询方案设置
	OECP_query_QuerySchemeListView : [__ctxPath + "/ext-oecp/core/ExtUtil.js",
		__ctxPath + "/js/component/function/Toast.js",
		__ctxPath + "/ext-oecp/ui/Button.js",
		__ctxPath + "/extjs/ext-basex.js",
		__ctxPath + "/ext-oecp/ui/button/ButtonManager.js",
		__ctxPath + "/ext-oecp/ui/Adapter.js",
		__ctxPath + "/ext-oecp/ui/AccordionTreePanel.js",
		__ctxPath + "/ext-oecp/ui/combo/OECPComboRef.js",
		__ctxPath + "/js/core/AppUtil.js",
		__ctxPath + "/ext-oecp/ui/QueryWindow.js",
		__ctxPath + "/js/component/querysetting/QuerySchemeListView.js",
		__ctxPath + "/js/component/querysetting/QueryConditionSettingPanel.js",
		__ctxPath + "/js/component/querysetting/QuerySchemeWindow.js"]
};

